FROM node:16.13-alpine
RUN mkdir -p /app/config /app/src
WORKDIR /app

# Install dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install

# Default command
CMD ["npm", "start"]